model: credit-risk
model_package_group: ModelCreditRisk
owner_bu: demo
environment: dev
target_column: default
steps:
  features:
    enabled: false
  train:
    enabled: true
    instance: ml.m5.xlarge
    framework_version: "1.2-1"
  evaluate:
    enabled: true
    instance: ml.m5.xlarge
  conditional_register:
    enabled: true
    metric: auc
    threshold: 0.75
deployment:
  target: bu-account
  account_id: "111111111111"
data:
  train_uri: s3://ml-platform-data/credit-risk/train/
